import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

public class book_newadd extends javax.swing.JFrame {

   
    public book_newadd() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        t4 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        t5 = new javax.swing.JComboBox();
        t6 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ADD A BOOK");
        setMinimumSize(new java.awt.Dimension(618, 464));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("BOOK ID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 40, 70, 30);
        getContentPane().add(t1);
        t1.setBounds(180, 50, 310, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("BOOK NAME");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 100, 90, 30);
        getContentPane().add(t4);
        t4.setBounds(180, 200, 310, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("AUTHOR");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 150, 70, 30);
        getContentPane().add(t3);
        t3.setBounds(180, 150, 310, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("PUBLICATION");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 200, 102, 30);
        getContentPane().add(t2);
        t2.setBounds(180, 100, 310, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel5.setForeground(new java.awt.Color(255, 51, 0));
        jLabel5.setText("AVAILABILITY");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 310, 110, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/address_book_add.png"))); // NOI18N
        jButton1.setText("ADD");
        jButton1.setToolTipText("click to add book");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(180, 370, 110, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Log-Out-icon (1).png"))); // NOI18N
        jButton2.setText("BACK");
        jButton2.setToolTipText("go back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(380, 370, 110, 30);

        t5.setFont(new java.awt.Font("Tahoma", 1, 14));
        t5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "YES", "NO" }));
        t5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t5ActionPerformed(evt);
            }
        });
        getContentPane().add(t5);
        t5.setBounds(180, 310, 90, 30);
        getContentPane().add(t6);
        t6.setBounds(180, 250, 310, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("TOPIC");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(110, 250, 50, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/globe_library_Wallpaper_xogc0.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 630, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            Connection con = DriverManager.getConnection("jdbc:odbc:library","admin","akshay");
            PreparedStatement pst = con.prepareStatement("insert into book values (?,?,?,?,?,?)");
            pst.setString(1,t1.getText());
            pst.setString(2,t2.getText());
            pst.setString(3,t3.getText());
            pst.setString(4,t4.getText());
            pst.setString(5,t6.getText());
            if
                    (t5.getSelectedIndex()==1)
                pst.setString(6,"YES");
            else
                pst.setString(6,"NO");
            pst.executeUpdate();
            con.close();
            JOptionPane.showMessageDialog(this,""+t2.getText().toUpperCase()+"\nBook is added");
            t1.setText("");
            t2.setText("");
            t3.setText("");
            t4.setText("");
            t6.setText("");
            
            
        } catch(Exception e){ System.out.println(e); }
}//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
        new main().setVisible(true);
        
}//GEN-LAST:event_jButton2ActionPerformed

    private void t5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t5ActionPerformed
        
}//GEN-LAST:event_t5ActionPerformed

   
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

           
            public void run() {
                new book_newadd().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JComboBox t5;
    private javax.swing.JTextField t6;
    // End of variables declaration//GEN-END:variables
}
