import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class book_issue extends javax.swing.JFrame {

    /** Creates new form book_issue */
    public book_issue() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jc1 = new javax.swing.JComboBox();
        jc2 = new javax.swing.JComboBox();
        jc3 = new javax.swing.JComboBox();
        b = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        c1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        t4 = new javax.swing.JTextField();
        c2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ISSUE A BOOK");
        setMinimumSize(new java.awt.Dimension(574, 574));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("BOOK ID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 50, 50, 14);

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("ISSUE DATE");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 370, 70, 14);
        getContentPane().add(t1);
        t1.setBounds(106, 41, 210, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search (2).png"))); // NOI18N
        jButton1.setText("Search Availability");
        jButton1.setToolTipText("search for availability");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(340, 45, 170, 30);

        jc1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "DATE", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jc1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jc1MouseClicked(evt);
            }
        });
        jc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jc1ActionPerformed(evt);
            }
        });
        getContentPane().add(jc1);
        jc1.setBounds(110, 360, 70, 30);

        jc2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MONTH", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        getContentPane().add(jc2);
        jc2.setBounds(200, 360, 80, 30);

        jc3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "YEAR", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2028", "2030" }));
        jc3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jc3ActionPerformed(evt);
            }
        });
        getContentPane().add(jc3);
        jc3.setBounds(300, 360, 70, 30);

        b.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        b.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Cute-Ball-Go-icon (1).png"))); // NOI18N
        b.setText("Issue book");
        b.setToolTipText("issue a book");
        b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActionPerformed(evt);
            }
        });
        getContentPane().add(b);
        b.setBounds(110, 430, 150, 30);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Actions-go-first-view-icon (3).png"))); // NOI18N
        jButton3.setText("    Back");
        jButton3.setToolTipText("go back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(320, 430, 120, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("AVAILABILITY");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 200, 79, 30);

        t2.setEditable(false);
        getContentPane().add(t2);
        t2.setBounds(106, 101, 210, 30);

        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });
        getContentPane().add(c1);
        c1.setBounds(108, 250, 210, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("BOOK NAME");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 110, 70, 14);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("MEMBER ID");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 260, 70, 14);

        t4.setEditable(false);
        getContentPane().add(t4);
        t4.setBounds(110, 200, 90, 30);

        c2.setEditable(false);
        getContentPane().add(c2);
        c2.setBounds(108, 300, 210, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("MEMBER NAME");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 310, 90, 14);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/comment_user_search.png"))); // NOI18N
        jButton4.setText("Varify Member");
        jButton4.setToolTipText("verify a member");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(340, 253, 180, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("AUTHOR");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 160, 50, 14);

        t3.setEditable(false);
        getContentPane().add(t3);
        t3.setBounds(106, 150, 210, 30);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/write-pen-book-ink-graphic-backgrounds-wallpapers.jpg"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 570, 570);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jc1ActionPerformed
    
        
    }//GEN-LAST:event_jc1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
dispose();
new main().setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      try{
    Class.forName("sun.jdbc.odbc.JdbcOdbcDriver"); 
    Connection con = DriverManager.getConnection("jdbc:odbc:library","admin","akshay");
    PreparedStatement pst = con.prepareStatement("select * from book where BOOK_ID=?");
    pst.setString(1,t1.getText());
       
    ResultSet rs = pst.executeQuery();
    if ( rs.next() ){
        t2.setText(rs.getString(2));
        t3.setText(rs.getString(3));
        t4.setText(rs.getString(6));
        
    }
    else
    {
        t2.setText("");t3.setText(""); t4.setText("");
     JOptionPane.showMessageDialog(this,"Sorry! No record is found");   
    }
    con.close();
    

    
   }
catch(Exception e){ System.out.println(e); }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
      try{
    Class.forName("sun.jdbc.odbc.JdbcOdbcDriver"); 
    Connection con = DriverManager.getConnection("jdbc:odbc:library","admin","akshay");
    PreparedStatement pst = con.prepareStatement("select * from member where MEMBERSHIP_ID=?");
    pst.setString(1,c1.getText());
       
    ResultSet rs = pst.executeQuery();
    if ( rs.next() ){
        c2.setText(rs.getString(2));
       
        
    }
    else
    {
        c2.setText("");
     JOptionPane.showMessageDialog(this,"Sorry! No record is found");   
    }
    con.close();
    
    

    
   }
catch(Exception e){ System.out.println(e); }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c1ActionPerformed

    private void bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActionPerformed
    

        
        try{
    Class.forName("sun.jdbc.odbc.JdbcOdbcDriver"); 
    Connection con = DriverManager.getConnection("jdbc:odbc:library","admin","akshay");
    PreparedStatement pst = con.prepareStatement("insert into transaction values(?,?,?,?,?,?,?,?,?)");
    pst.setString(1,t1.getText());
    pst.setString(2,t2.getText());
    pst.setString(3,t3.getText());
    pst.setString(4,c1.getText());
    pst.setString(5,c2.getText());
    pst.setString(6,t4.getText());
    pst.setString(7,jc1.getSelectedItem().toString());
    pst.setString(8,jc2.getSelectedItem().toString());
    pst.setString(9,jc3.getSelectedItem().toString());
    
    
    
            pst.executeUpdate();
            con.close();
             try{
    Class.forName("sun.jdbc.odbc.JdbcOdbcDriver"); 
    Connection con1 = DriverManager.getConnection("jdbc:odbc:library","admin","akshay");
    PreparedStatement pst1 = con1.prepareStatement("update book set AVAIL_STATUS=? where BOOK_ID=?");
    pst1.setString(1,"NO");
    pst1.setString(2,t1.getText());
    pst1.executeUpdate();
    con1.close();
     }
     catch(Exception z){ System.out.println(z); }
             try{
    Class.forName("sun.jdbc.odbc.JdbcOdbcDriver"); 
    Connection con2 = DriverManager.getConnection("jdbc:odbc:library","admin","akshay");
    PreparedStatement pst2 = con2.prepareStatement("delete from fine where BOOK_ID=?");
    pst2.setString(1,t1.getText());
    pst2.executeUpdate();
    con2.close();
     }
     catch(Exception x){ System.out.println(x); }
     JOptionPane.showMessageDialog(this,""+t2.getText().toUpperCase()+"\n1 Book is issued");
            t1.setText("");
            t2.setText("");
            t3.setText("");
            t4.setText("");
            c1.setText("");
            c2.setText("");
            
        }        
catch(Exception e)
{ System.out.println(e);} 
    }//GEN-LAST:event_bActionPerformed

    private void jc3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jc3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jc3ActionPerformed

    private void jc1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jc1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jc1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new book_issue().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b;
    private javax.swing.JTextField c1;
    private javax.swing.JTextField c2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JComboBox jc1;
    private javax.swing.JComboBox jc2;
    private javax.swing.JComboBox jc3;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    // End of variables declaration//GEN-END:variables
}
