/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * book_return.java
 *
 * Created on Feb 5, 2012, 11:54:37 PM
 */
/**
 *
 * @author amit
 */
import java.sql.*;
import javax.swing.JOptionPane;
import java.lang.*;
import java.util.*;
public class book_return extends javax.swing.JFrame {

    /** Creates new form book_return */
    public book_return() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        c3 = new javax.swing.JComboBox();
        c2 = new javax.swing.JComboBox();
        c1 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        t4 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        t5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        t7 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        t6 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BOOK RETURN");
        setMinimumSize(new java.awt.Dimension(664, 612));
        setResizable(false);
        getContentPane().setLayout(null);

        c3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "YEAR", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2028", "2030" }));
        getContentPane().add(c3);
        c3.setBounds(350, 360, 80, 30);

        c2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MONTH", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        getContentPane().add(c2);
        c2.setBounds(240, 360, 90, 30);

        c1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "DATE", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });
        getContentPane().add(c1);
        c1.setBounds(150, 360, 70, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("SUBMISSION DATE");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 370, 120, 15);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("BOOK ID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 80, 60, 15);
        getContentPane().add(t1);
        t1.setBounds(150, 75, 340, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/edit-icon.png"))); // NOI18N
        jButton1.setText("Fine calulator");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(100, 510, 150, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Cute-Ball-Go-icon (1).png"))); // NOI18N
        jButton2.setText("Submit book");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(280, 510, 150, 30);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Actions-go-first-view-icon (3).png"))); // NOI18N
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(460, 510, 110, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("BOOK NAME");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 140, 80, 15);

        t2.setEditable(false);
        getContentPane().add(t2);
        t2.setBounds(150, 130, 340, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("MEMBER ID");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 200, 80, 15);

        t3.setEditable(false);
        getContentPane().add(t3);
        t3.setBounds(150, 190, 340, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("MEMBER NAME");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 260, 100, 15);

        t4.setEditable(false);
        getContentPane().add(t4);
        t4.setBounds(150, 250, 340, 30);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search (2).png"))); // NOI18N
        jButton4.setText("Search");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(540, 70, 100, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("ISSUE DATE");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(60, 320, 80, 15);

        t5.setEditable(false);
        getContentPane().add(t5);
        t5.setBounds(150, 310, 160, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("FINE");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(110, 470, 30, 15);

        t7.setEditable(false);
        getContentPane().add(t7);
        t7.setBounds(150, 460, 120, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("FINE DATE");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(70, 420, 70, 15);

        t6.setEditable(false);
        getContentPane().add(t6);
        t6.setBounds(150, 410, 120, 30);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/SB0130x_b.jpg"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 670, 590);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_c1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
dispose();
new main().setVisible(true);

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
     try{
    Class.forName("sun.jdbc.odbc.JdbcOdbcDriver"); 
    Connection con = DriverManager.getConnection("jdbc:odbc:library","admin","akshay");
    PreparedStatement pst = con.prepareStatement("select * from transaction where BOOK_ID=?");
    pst.setString(1,t1.getText());
       
    ResultSet rs = pst.executeQuery();
    if ( rs.next() ){
    t2.setText(rs.getString("BOOK_NAME"));
    t3.setText(rs.getString("MEMBER_ID"));
    t4.setText(rs.getString("MEMBER_NAME"));
    String d=rs.getString(7);
    String m=rs.getString(8);
    String y=rs.getString(9);
    t5.setText(d+" / "+m+" /"+y);
     }
    else
    {
        t2.setText(""); t3.setText("");t4.setText("");
     JOptionPane.showMessageDialog(this,"Sorry! No record is found");   
    }
    con.close();
    
   }
catch(Exception e){ System.out.println(e); }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     try{
    Class.forName("sun.jdbc.odbc.JdbcOdbcDriver"); 
    Connection con = DriverManager.getConnection("jdbc:odbc:library","admin","akshay");
    PreparedStatement pst = con.prepareStatement("select * from transaction where BOOK_ID=?");
    pst.setString(1,t1.getText());
       
    ResultSet rs = pst.executeQuery();
    if ( rs.next() ){
     Calendar cal1 = new GregorianCalendar();
     Calendar cal2 = new GregorianCalendar();
     int a=Integer.parseInt(rs.getString(7));//Date of issue
     int b=Integer.parseInt(rs.getString(8));//Month of issue
     int c=Integer.parseInt(rs.getString(9));//Year of issue
     cal1.set(c, b, a);
     int a1=Integer.parseInt(c1.getSelectedItem().toString());//Date of submission
     int b1=Integer.parseInt(c2.getSelectedItem().toString());//Month of submission
     int c1=Integer.parseInt(c3.getSelectedItem().toString());//Year of submission
     cal2.set(c1, b1, a1);
     long milis1 = cal1.getTimeInMillis();
     long milis2 = cal2.getTimeInMillis();
     long diff = milis2 - milis1;
     long d = diff/(24 * 60 * 60 * 1000);
     long f;
     if(a>24)
     {if(b==12)
     {t6.setText(((a+7)-31)+" / "+(1)+" / "+(c+1));
     }
     else
     {t6.setText(((a+7)-31)+" / "+(b+1)+" / "+c);}
     }
     else
     {t6.setText((a+7)+" / "+b+" / "+c);
     }
     if(d<=7){JOptionPane.showMessageDialog(this,"No fines due","Information",JOptionPane.INFORMATION_MESSAGE);
     t7.setText("   nil.  ");
     }
     else{
        f=((d-7)*5);
        String z=Long.toString(f);
        t7.setText("Rs." +z);
       
         
         }
     }
    else
    {
          
    }
    con.close();
    
   }
catch(Exception e){ System.out.println(e); }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 try{
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            Connection con = DriverManager.getConnection("jdbc:odbc:library","admin","akshay");
            PreparedStatement pst = con.prepareStatement("insert into fine values (?,?,?,?,?,?,?,?)");
            pst.setString(1,t1.getText());
            pst.setString(2,t2.getText());
            pst.setString(3,t3.getText());
            pst.setString(4,t4.getText());
            pst.setString(5,t5.getText());
            pst.setString(6,(c1.getSelectedItem().toString()+"/ "+c2.getSelectedItem().toString()+"/ "+c3.getSelectedItem().toString()));
            pst.setString(7,t6.getText());
            pst.setString(8,t7.getText());
           
            pst.executeUpdate();
            con.close();
            try{
    Class.forName("sun.jdbc.odbc.JdbcOdbcDriver"); 
    Connection con1 = DriverManager.getConnection("jdbc:odbc:library","admin","akshay");
    PreparedStatement pst1 = con1.prepareStatement("update book set AVAIL_STATUS=? where BOOK_ID=?");
    pst1.setString(1,"YES");
    pst1.setString(2,t1.getText());
    pst1.executeUpdate();
    con1.close();
     }
     catch(Exception z){ System.out.println(z); }
      try{
    Class.forName("sun.jdbc.odbc.JdbcOdbcDriver"); 
    Connection con2 = DriverManager.getConnection("jdbc:odbc:library","admin","akshay");
    PreparedStatement pst2 = con2.prepareStatement("delete from transaction where BOOK_ID=?");
    pst2.setString(1,t1.getText());
    pst2.executeUpdate();
    con2.close();
     }
     catch(Exception x){ System.out.println(x); }      
            JOptionPane.showMessageDialog(this,""+t2.getText().toUpperCase()+"\n1 Book is submitted succesfully");
            t1.setText("");
            t2.setText("");
            t3.setText("");
            t4.setText("");
            t5.setText("");
            t6.setText("");
            t7.setText("");
            
            
        } catch(Exception e){ System.out.println(e); }      
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new book_return().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox c1;
    private javax.swing.JComboBox c2;
    private javax.swing.JComboBox c3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    private javax.swing.JTextField t7;
    // End of variables declaration//GEN-END:variables
}
