
import com.sun.corba.se.impl.protocol.giopmsgheaders.ReplyMessage;
import java.sql.*;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


public class book_remove extends javax.swing.JFrame {

    /** Creates new form book_remove */
    public book_remove() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        t = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("REMOVE A BOOK");
        setMinimumSize(new java.awt.Dimension(621, 466));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("BOOK ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 140, 60, 15);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Cute-Ball-Go-icon (1).png"))); // NOI18N
        jButton1.setText("Verify");
        jButton1.setToolTipText("click to remove book");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(80, 290, 110, 30);
        getContentPane().add(t);
        t.setBounds(170, 130, 310, 30);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Actions-go-first-view-icon (3).png"))); // NOI18N
        jButton3.setText("Back");
        jButton3.setToolTipText("go back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(380, 290, 120, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/address_book_delete.png"))); // NOI18N
        jButton2.setText("Remove");
        jButton2.setToolTipText("remove a book");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(220, 290, 130, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("BOOK NAME");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 200, 80, 15);
        getContentPane().add(t1);
        t1.setBounds(170, 190, 310, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/remove.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 620, 465);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
        new main().setVisible(true);
        // TODO add your handling code here:
}//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      try{
    Class.forName("sun.jdbc.odbc.JdbcOdbcDriver"); 
    Connection con = DriverManager.getConnection("jdbc:odbc:library","admin","akshay");
    PreparedStatement pst = con.prepareStatement("select NAME from book where BOOK_ID=?");
    pst.setString(1,t.getText());
       
    ResultSet rs = pst.executeQuery();
    if ( rs.next() ){
        
        t1.setText(rs.getString("NAME"));
        JOptionPane.showMessageDialog(this,"1 Book found","Information",JOptionPane.INFORMATION_MESSAGE);
        
        
      
    }
    else
    {
        t.setText("");
     JOptionPane.showMessageDialog(this,"Sorry! No record is found","Error",JOptionPane.ERROR_MESSAGE);   
    }
    con.close();
    

    
   }
catch(Exception e){ System.out.println(e); }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     try{
    Class.forName("sun.jdbc.odbc.JdbcOdbcDriver"); 
    Connection con = DriverManager.getConnection("jdbc:odbc:library","admin","akshay");
    PreparedStatement pst = con.prepareStatement("delete from book where BOOK_ID=?");
    pst.setString(1,t.getText());
    int reply=JOptionPane.showConfirmDialog(this,"Are you sure you want to delete this book","CONFIRMATION",JOptionPane.YES_NO_OPTION);
    if (reply == JOptionPane.YES_OPTION){
      int a = pst.executeUpdate();  
      t.setText(""); t1.setText("");
      JOptionPane.showMessageDialog(this,""+t1.getText().toUpperCase()+"\nBook is removed"); }
    else if(reply == JOptionPane.NO_OPTION)
    { setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
    }
    
    
       
    
    con.close();
     }
catch(Exception e){ System.out.println(e); } 
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new book_remove().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField t;
    private javax.swing.JTextField t1;
    // End of variables declaration//GEN-END:variables
}
