public class main extends javax.swing.JFrame {

    /** Creates new form main */
    public main() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        c2 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        c1 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        c3 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Welcome Administrartor");
        setMinimumSize(new java.awt.Dimension(701, 412));
        setResizable(false);
        getContentPane().setLayout(null);

        c2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "select", "search book", "search member" }));
        c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2ActionPerformed(evt);
            }
        });
        getContentPane().add(c2);
        c2.setBounds(270, 130, 120, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SEARCH");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(180, 120, 80, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ADMINISTRATIVE TASKS");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 47, 230, 50);

        c1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "select", "add member", "remove member", "edit member", "add book", "remove book", "issue book", "recieve book" }));
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });
        getContentPane().add(c1);
        c1.setBounds(270, 60, 120, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("VIEW");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(200, 190, 60, 40);

        c3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "select", "all members", "all books", "all issued books", "all submitted books" }));
        getContentPane().add(c3);
        c3.setBounds(270, 197, 120, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Actions-go-next-icon (2).png"))); // NOI18N
        jButton1.setText("Go");
        jButton1.setToolTipText("go");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(450, 60, 90, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Actions-go-next-icon (2).png"))); // NOI18N
        jButton2.setText("Go");
        jButton2.setToolTipText("go");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(450, 130, 90, 30);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Actions-go-next-icon (2).png"))); // NOI18N
        jButton3.setText("Go");
        jButton3.setToolTipText("go");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(450, 200, 90, 30);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Button-Log-Off-icon (1).png"))); // NOI18N
        jButton4.setText("LOG OUT");
        jButton4.setToolTipText("click to logout");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(268, 255, 140, 40);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/encrypted.png"))); // NOI18N
        jButton5.setText("Change Password");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(490, 320, 180, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/admin.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 700, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2ActionPerformed
        
    }//GEN-LAST:event_c2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
if(c1.getSelectedIndex()==1)
{
    dispose();
    new member_add().setVisible(true);
    
}
if(c1.getSelectedIndex()==2)
{
    dispose();
    new member_remove().setVisible(true);
    
    }

if(c1.getSelectedIndex()==3)
{
    dispose();
    new member_edit().setVisible(true);
    
}
if(c1.getSelectedIndex()==4)
{
    dispose();
    new book_newadd().setVisible(true);
    
}
if(c1.getSelectedIndex()==5)
{
    dispose();
    new book_remove().setVisible(true);
    
}
 if(c1.getSelectedIndex()==6)
{
    dispose();
    new book_issue().setVisible(true);
    
}  
 if(c1.getSelectedIndex()==7)
{
    dispose();
    new book_return().setVisible(true);
    
}// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
if(c2.getSelectedIndex()==2)
{
    dispose();
    new member_search().setVisible(true);
    
} 
if(c2.getSelectedIndex()==1)
{
    dispose();
    new book_search().setVisible(true);
    
} 
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
if(c3.getSelectedIndex()==1)
{
    dispose();
    new member_all().setVisible(true);
    
}   
if(c3.getSelectedIndex()==2)
{
    dispose();
    new book_adminviewall().setVisible(true);
    
} 
if(c3.getSelectedIndex()==3)
{dispose();
new IssuedBook_viewall().setVisible(true);
}
if(c3.getSelectedIndex()==4)
{dispose();
new submittedbooks_viewall().setVisible(true);
}
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        
  dispose();
new lib().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c1ActionPerformed

private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
dispose();
new changepassword().setVisible(true);
}//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new main().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox c1;
    private javax.swing.JComboBox c2;
    private javax.swing.JComboBox c3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
