
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * member_remove.java
 *
 * Created on Feb 5, 2012, 9:46:21 PM
 */
/**
 *
 * @author amit
 */
public class member_remove extends javax.swing.JFrame {

    /** Creates new form member_remove */
    public member_remove() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("REMOVE A MEMBER");
        setMinimumSize(new java.awt.Dimension(660, 460));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("MEMBERSHIP ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 130, 101, 15);
        getContentPane().add(t1);
        t1.setBounds(190, 120, 300, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Cute-Ball-Go-icon (1).png"))); // NOI18N
        jButton1.setText("Verify");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(100, 280, 110, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user_blue_delete.png"))); // NOI18N
        jButton2.setText("Remove");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(240, 280, 120, 30);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Actions-go-first-view-icon (3).png"))); // NOI18N
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(390, 280, 110, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("                NAME");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 190, 99, 15);
        getContentPane().add(t2);
        t2.setBounds(190, 180, 300, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/remove-user-icon.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 665, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
dispose();
new main().setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
    Class.forName("sun.jdbc.odbc.JdbcOdbcDriver"); 
    Connection con = DriverManager.getConnection("jdbc:odbc:library","admin","akshay");
    PreparedStatement pst = con.prepareStatement("select NAME from member where MEMBERSHIP_ID=?");
    pst.setString(1,t1.getText());
       
    ResultSet rs = pst.executeQuery();
    if ( rs.next() ){
        
        t2.setText(rs.getString("NAME"));
        JOptionPane.showMessageDialog(this,"1 Member found","Information",JOptionPane.INFORMATION_MESSAGE);
        
        
      
    }
    else
    {
        t1.setText("");
     JOptionPane.showMessageDialog(this,"Sorry! No record is found","Error",JOptionPane.ERROR_MESSAGE);   
    }
    con.close();
    

    
   }
catch(Exception e){ System.out.println(e); }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     try{
    Class.forName("sun.jdbc.odbc.JdbcOdbcDriver"); 
    Connection con = DriverManager.getConnection("jdbc:odbc:library","admin","akshay");
    PreparedStatement pst = con.prepareStatement("delete from member where MEMBERSHIP_ID=?");
    pst.setString(1,t1.getText());
    int reply=JOptionPane.showConfirmDialog(this,"Are you sure you want to remove this member","CONFIRMATION",JOptionPane.YES_NO_OPTION);
    if (reply == JOptionPane.YES_OPTION){
      int a = pst.executeUpdate();
      JOptionPane.showMessageDialog(this,""+t2.getText().toUpperCase()+"\nMember is removed");
      t1.setText(""); t2.setText("");
       }
    else if(reply == JOptionPane.NO_OPTION)
    { setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
    }
    
    
       
    
    con.close();
     }
catch(Exception e){ System.out.println(e); } 
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new member_remove().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    // End of variables declaration//GEN-END:variables
}
