
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * member_edit.java
 *
 * Created on Feb 5, 2012, 10:24:12 PM
 */
/**
 *
 * @author amit
 */
public class member_edit extends javax.swing.JFrame {

    /** Creates new form member_edit */
    public member_edit() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        t4 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        t1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        t5 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        t6 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EDIT MEMBERSHIP DETAILS");
        setMinimumSize(new java.awt.Dimension(747, 445));
        setResizable(false);
        getContentPane().setLayout(null);
        getContentPane().add(t4);
        t4.setBounds(240, 180, 280, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("ADDRESS");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(150, 190, 60, 15);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Actions-go-first-view-icon (3).png"))); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(400, 340, 120, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/edit-icon.png"))); // NOI18N
        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(240, 340, 120, 30);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search (2).png"))); // NOI18N
        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(550, 30, 100, 30);
        getContentPane().add(t1);
        t1.setBounds(240, 30, 280, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel7.setText("MEMBERSHIP ID");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(110, 40, 110, 15);
        getContentPane().add(t3);
        t3.setBounds(240, 130, 280, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("E-MAIL");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(160, 140, 50, 15);
        getContentPane().add(t2);
        t2.setBounds(240, 80, 280, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel9.setText("NAME");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(170, 90, 40, 15);
        getContentPane().add(t5);
        t5.setBounds(240, 230, 280, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("AGE");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(180, 240, 30, 15);
        getContentPane().add(t6);
        t6.setBounds(240, 280, 280, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("PHONE");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(170, 290, 60, 15);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/akshay1.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 750, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
        new main().setVisible(true);// TODO add your handling code here:
}//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     try{
    Class.forName("sun.jdbc.odbc.JdbcOdbcDriver"); 
    Connection con = DriverManager.getConnection("jdbc:odbc:library","admin","akshay");
    PreparedStatement pst = con.prepareStatement("update member set NAME=?, E-MAIL=?, ADDRESS=?, AGE=?, PHONE=? where MEMBERSHIP_ID=?");
    
    pst.setString(1,t2.getText());
    pst.setString(2,t3.getText());
    pst.setString(3,t4.getText());
    pst.setString(4,t5.getText());
    pst.setString(5,t6.getText());
    pst.setString(6,t1.getText());
    pst.executeUpdate();
    con.close();
    JOptionPane.showMessageDialog(this,"1 Record updated Successfully","Success",JOptionPane.INFORMATION_MESSAGE);
    t1.setText("");
    t2.setText("");
    t3.setText("");
    t4.setText("");
    t5.setText("");
    t6.setText("");
     }
catch(Exception e){ System.out.println(e); }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      try{
    Class.forName("sun.jdbc.odbc.JdbcOdbcDriver"); 
    Connection con = DriverManager.getConnection("jdbc:odbc:library","admin","akshay");
    PreparedStatement pst = con.prepareStatement("select * from member where MEMBERSHIP_ID=?");
    pst.setString(1,t1.getText());
       
    ResultSet rs = pst.executeQuery();
    if ( rs.next() ){
        t2.setText(rs.getString(2));
        t3.setText(rs.getString(3));
        t4.setText(rs.getString(4));
        t5.setText(rs.getString(5));
        t6.setText(rs.getString(6));
    }
    else
    {
        t2.setText(""); t3.setText("");t4.setText("");t5.setText("");t6.setText("");
     JOptionPane.showMessageDialog(this,"Sorry! No record is found");   
    }
    con.close();
    
   }
catch(Exception e){ System.out.println(e); }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new member_edit().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    // End of variables declaration//GEN-END:variables
}
