

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.JFrame;
import java.util.*;


/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * member_search.java
 *
 * Created on Feb 11, 2012, 4:44:59 PM
 */
/**
 *
 * @author AKKI
 */
public class member_search extends javax.swing.JFrame {

    /** Creates new form member_search */
    public member_search() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        t6 = new javax.swing.JTextField();
        t7 = new javax.swing.JTextField();
        t8 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        t4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        t5 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SEARCH FOR MEMBERS");
        setBackground(java.awt.Color.white);
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 707, 530));
        setMinimumSize(new java.awt.Dimension(685, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel1.setText("MEMBERSHIP ID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 65, 101, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel2.setText("NAME");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(160, 125, 35, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel3.setText("E-MAIL");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(150, 190, 44, 15);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel4.setText("PHONE");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(160, 330, 41, 15);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel5.setText("MEMBERSHIP ISSUE DATE");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 370, 159, 15);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel6.setText("MEMBERSHIP EXPIRY DATE");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 430, 167, 15);
        getContentPane().add(t1);
        t1.setBounds(220, 60, 270, 30);

        t2.setEditable(false);
        t2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(t2);
        t2.setBounds(220, 120, 270, 30);

        t3.setEditable(false);
        getContentPane().add(t3);
        t3.setBounds(220, 180, 270, 30);

        t6.setEditable(false);
        getContentPane().add(t6);
        t6.setBounds(220, 320, 170, 30);

        t7.setEditable(false);
        getContentPane().add(t7);
        t7.setBounds(220, 360, 270, 30);

        t8.setEditable(false);
        getContentPane().add(t8);
        t8.setBounds(220, 420, 270, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search (2).png"))); // NOI18N
        jButton1.setText("SEARCH");
        jButton1.setToolTipText("click to search a member");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(520, 60, 110, 25);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Actions-draw-eraser-icon (1).png"))); // NOI18N
        jButton2.setText("RESET");
        jButton2.setToolTipText("click to reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(210, 490, 114, 41);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Actions-go-first-view-icon (3).png"))); // NOI18N
        jButton3.setText("BACK");
        jButton3.setToolTipText("click to go back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(390, 490, 106, 41);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel7.setText("ADDRESS");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(140, 240, 59, 15);

        t4.setEditable(false);
        getContentPane().add(t4);
        t4.setBounds(220, 230, 270, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel8.setText("AGE");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(170, 290, 30, 10);

        t5.setEditable(false);
        getContentPane().add(t5);
        t5.setBounds(220, 280, 70, 30);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/textmining.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 500, 375);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/book_animation.gif"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(300, 270, 390, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       t1.setText("");
       t2.setText("");
       t3.setText("");
       t4.setText("");
       t5.setText("");
       t6.setText("");
       t7.setText("");
       t8.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
     try{
    Class.forName("sun.jdbc.odbc.JdbcOdbcDriver"); 
    Connection con = DriverManager.getConnection("jdbc:odbc:library","admin","akshay");
    PreparedStatement pst = con.prepareStatement("select * from member where MEMBERSHIP_ID=?");
    pst.setString(1,t1.getText());
       
    ResultSet rs = pst.executeQuery();
    if ( rs.next() ){
        t2.setText(rs.getString(2));
        t3.setText(rs.getString(3));
        t4.setText(rs.getString(4));
        t5.setText(rs.getString(5));
        t6.setText(rs.getString(6));
        
        String date1;
        date1=rs.getString(7)+"/"+rs.getString(8)+"/"+rs.getString(9);
        t7.setText(date1);
       
        String date2;
        date2=rs.getString(10)+"/"+rs.getString(11)+"/"+rs.getString(12);
        t8.setText(date2);
        
        
    }
    else
    {
        t2.setText(""); t3.setText("");t4.setText("");t5.setText("");t6.setText("");t7.setText("");t8.setText("");
      
     JOptionPane.showMessageDialog(this,"Sorry! No record is found");   
    }
    con.close();
    

    
   }
catch(Exception e){ System.out.println(e); }
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      dispose();
new main().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new member_search().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    private javax.swing.JTextField t7;
    private javax.swing.JTextField t8;
    // End of variables declaration//GEN-END:variables
}
